// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package wrods

import (
	"star/api/wrods"
)

type ControllerV1 struct{}

func NewV1() wrods.IWrodsV1 {
	return &ControllerV1{}
}
